#!/bin/bash

INSTALL_PATH=~/.local/share/aiprj

if [ -z "$1" ]; then
  echo "引数がありません。"
  echo "[Usage] "$0" 作成するディレクトリ名"
  exit 1
fi

echo "Setup AI Project: "$1

if [ -d $1 ]; then
  echo "既存のディレクトリをアップデートします。"
else
  mkdir $1
fi

cp -r $INSTALL_PATH/.claude $1/
cp -r $INSTALL_PATH/.gemini $1/
cp -r $INSTALL_PATH/.aiprj $1/

cp $INSTALL_PATH/.mcp.json $1/

if [ -f $1/.aiprj/instructions.md ]; then
  echo "------------------------------"
  echo "Now Instructions"
  echo "------------------------------"
  cat $1/.aiprj/instructions.md
  echo ""
  echo "------------------------------"
  rm $1/.aiprj/instructions.md.org
else
  cat $INSTALL_PATH/.aiprj/instructions.md.org > $1/.aiprj/instructions.md
fi

if [ -f $1/.gitignore ]; then
  cat $1/.gitignore > $1/.gitignore.org
  cat $INSTALL_PATH/.gitignore.org $1/.gitignore.org > $1/.gitignore
else
  cat $INSTALL_PATH/.gitignore.org > $1/.gitignore
fi
